feat: `w3 key create`
web3-storage/w3cli pull request #155
Opened 2024-01-10 16:33 UTC by olizilla

Print a new key pair. Does not change your current signing key.

Bring the feature from [`ucan-key`](https://github.com/olizilla/ucan-key) into w3cli

```shell
$ ./bin.js key create
# did:key:z6Mkne1JnNWCvUgxsdo552FW8jRN78uxbpCnBmDiPmf1koYc
MgCZ5ftHm9e0FnNtFXA2sMZgcf97GO4vTaybGEfkBp/KR5+0BeZ44TKEOwUjbLqvFFs2hpFxD++IAEEL+3ySROyDsSRk=

$ ./bin.js key create --json | jq
{
  "id": "did:key:z6MkkMAAvj6KDQgLMPbdow6Y1Pkw1HCZ5d7xYs5GbpgiUbKk",
  "keys": {
    "did:key:z6MkkMAAvj6KDQgLMPbdow6Y1Pkw1HCZ5d7xYs5GbpgiUbKk": {
      "/": {
        "bytes": "gCYGer62xpRcHSqBrAuegMwG+pja12caVYwlEUFx0kT8TO0BV5X+2K+9uE3GvSKUFFanWcoewsJN1hU3a2MTqxPLGe8"
      }
    }
  }
}
```

- the json output is dag-json encoded archive from ucanto Signer.

see: https://github.com/web3-storage/w3cli/issues/154#issuecomment-1885042715

License: MIT

2024-01-11 10:23 UTC, alanshaw requested changes

2024-01-11 10:23 UTC, alanshaw commented on README.md
> +- [`w3 key create`](#w3-key-create)
```suggestion
  - [`w3 key create`](#w3-key-create)
```

2024-01-11 10:23 UTC, alanshaw commented on README.md
> +  > By registering your w3up beta Space with [web3.storage](http://web3.storage/), you agree to the w3up beta [Terms of Service](https://console.web3.storage/terms). Until the beta period is over and
```suggestion
```

2024-01-11 10:23 UTC, alanshaw commented on bin.js
> +  .describe('Print a new key pair. Does not change your current signing key')
```suggestion
  .describe('Generate and print a new ed25519 key pair. Does not change your current signing key.')
```

2024-01-11 10:23 UTC, alanshaw commented on index.js
> +import { ed25519, RSA } from '@ucanto/principal'
`RSA` unused?

2024-01-11 10:23 UTC, alanshaw commented on index.js
> +    console.log(`${key}`)
Is it already a string?
```suggestion
    console.log(key)
```

2024-01-12 14:45 UTC, olizilla commented
I bow deeply in apology for the prettier noise. tis an obnoxious and persistent bot, and I let my guard down. As the harm is now done, I leave it in this PR so others do not suffer the same semantically-meaningless, unrelated change fate.

2024-01-15 14:02 UTC, alanshaw approved these changes

2024-01-15 15:12 UTC, alanshaw commented
I merge this so I can do some other readme cleanup.

2024-01-15 15:12 UTC, merged